# Generated by Django 4.2.13 on 2024-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_serial_number', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('glucose_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
